rapidpro/rapidpro

temba/api/serializers.py, temba/api/tests.py, temba/api/views.py
adds `expires` (in minutes) to the Flow read API endpoint (https://rapidpro.io/api/v1/flows)
adds `expires_on` and `expired_on` to the FlowRun read API endpoint (https://rapidpro.io/api/v1/runs)
see also https://github.com/rapidpro/rapidpro/issues/179
=> expose flow and run expirations via api

templates/orgs/org_create_login.haml
The javascript on this page was always hiding the create_login form,
even when errors were rendered. Now we show the create_login form if there are errors.
=> Show the create login form on page load if there are form errors. Fixes #193.

static/coffee/flows/services.coffee
Flow service "flow completion" fetch should not iterate through null variables.
It resulted in "Array.prototype.slice called on null or undefined" with Chrome launcher thus some tests failed.
This fix will ensure both PhantomJS and Chrome browsers to have same results.
=> fix running karma tests with Chrome browser and debugging

.gitignore, Vagrantfile, ansible.cfg, ansible/ansible.cfg, ansible/requirements.yml, ansible/roles/rapidpro/defaults/main.yml, ansible/roles/rapidpro/meta/main.yml, ansible/roles/rapidpro/tasks/main.yml, ansible/roles/rapidpro/tasks/npm.yml, ansible/roles/rapidpro/tasks/postgres.yml, ansible/roles/rapidpro/tasks/python.yml, ansible/site.yml, ansible/vars.yml
Vagrant developer environment. #145 
Only two dependencies, Vagrant and Ansible.
I use Ansible to configure and manage the developer environment because the configuration is cleaner and often self-explanatory. :-)
The developer environment would work as follows.
```bash
cd rapidpro/ansible
ansible-galaxy install -r requirements.yml
cd ..
vagrant up --provision
```
When It finishes:
```bash
vagrant ssh
cd rapidpro
source .venv/bin/activate
python manage.py runserver 0.0.0.0:8000
```
Then if you go in your browser to `http://localhost:8000` you're good to go!
I'll update the development gh-page configuration if you're ok with this PR.
=> Vagrant developer environment

temba/flows/migrations/0060_flowrun_timeout_on.py, temba/flows/migrations/0061_exit_flowruns.py, temba/flows/migrations/0062_flowlabel_uuid.py
Running migration flows.60 throws this:
"django.db.utils.ProgrammingError: column flows_flowrun.timeout_on does not exist"
That column was only added in 61, so I fixed the order of dependencies
=> fix migration dependencies/ordering

templates/includes/nav.haml
=> add missing temba template tag library to templates/includes/nav.haml

_docs/development.md
Updates the onboarding documentation to use `python manage.py migrate` rather than `python manage.py syncdb`.
Related fix for Ansible: #437
=> Update onboarding documentation for Django upgrade command

ansible/roles/rapidpro/tasks/python.yml
Simple fix changes Ansible script to run `python manage.py migrate` rather than `python manage.py syncdb`.
Associated documentation upgrade: #438
=> Fix Django upgrade breaking Ansible provisioning

pip-freeze.txt
pip-freeze.txt wants 4.0.12 which breaks on Alpine Linux, 4.0.13 fixes that. 
Alpine is used for the rapidpro docker images and so the docker builds are broken because of the 4.0.12 dependency.
=> Upgrade to Alpine linux friendly version of python-magic

temba/channels/views.py, templates/channels/channel_configuration.haml
This makes use of an `add_config_fields` hook which doesn't seem to be used anywhere else.
Also it addresses (what seems to be) a bug in the `pre_save()` function where every field value was turned into a bool.
=> Show Junebug config for USSD channel and use Radio buttons for selecting channel type.

temba/channels/tests.py
The test case is is hitting api.plivo.com. Came across this while running tests offline and spotted the TCP error.
=> Plivo release calls requests.delete, not requests.post. 

temba/channels/models.py, temba/channels/tests.py
Junebug doesn't want the `from` nor `to` values specified when a message id is given as a `reply_to`
=> Do not specify to & from when using reply_to in Junebug channel

temba/channels/models.py, temba/channels/tests.py
Currently it just crashes and logs an `id` in the channel log which is not all that useful.
=> Sometimes the `id` is not available from Junebug, log when that happens

temba/channels/handlers.py, temba/channels/tests.py
An event in isolation does not give us enough to determine whether or not the original message was a USSD message or not.
This change makes sure the channel is one of the two known Junebug channel types and then handles the event.
=> Fix USSD event handling for Junebug

temba/channels/tests.py, temba/flows/models.py, temba/ussd/models.py
When starting a USSD session, the first message isn't saved and used in the Flow as the `start_msg`. This means that the first reply the Flow sends back has no `response_to` set. When USSD channels (Like Vumi and Junebug) try to send a reply they often need to refer back to the `external_id` of the `response_to` object to allow the integrations to link back to an actively running USSD session.
This PR should address that.
=> Create a first message for when starting a USSD Flow

temba/channels/tests.py, temba/ussd/models.py
This causes template rendering problems because the `msg.direction` should always be truth-y.
=> The first Msg created for USSD Pull sessions has no direction set.

pip-freeze.txt, pip-requires.txt, temba/locations/management/commands/download_geojson.py, temba/locations/tests.py
This accompanies the `import_geojson` management command. It takes OSM relation ids as positional arguments and then downloads the relevant files from a GitHub repository. It defaults to `nyaruka/posm-extracts`.
=> Management command to download OSM extracts for relation ids

temba/channels/models.py, temba/channels/tests.py, templates/channels/channel_read.haml
Currently they're only accessible by manually constructing the URL and providing the correct primary key for the `?channel=` parameter.
=> Display links to channel logs for USSD channels.

temba/locations/management/commands/import_geojson.py
This PR addresses two things:
1. Really skip when not matching a file instead of printing that we're skipping.
2. Allow loading geojson files from directories instead of assuming it is in the current directory.
=> Fix GeoJSON loading from directories.

templates/flows/simulator.haml
Whitenoise does not appreciate the extra forward slash.
before:
after:
=> Fix simulator background when using Whitenoise to serve statics.

_docs/development.md
Django startup fails with an obscure warnings about settings not being available if libmagic isn't installed.
=> libmagic needs to be installed to get set up.

temba/msgs/models.py, temba/msgs/tests.py, temba/settings.py.dev
We were experiencing issues with our USSD service, our sentry was showing these errors:
```
IntegrityError: insert or update on table "channels_channellog" violates foreign key constraint "channels_channellog_msg_id_e40e6612_fk_msgs_msg_id"
DETAIL:  Key (msg_id)=(260040) is not present in table "msgs_msg".
```
After investigating I found the message object would always exist in the DB, but the queue started processing the message before the original transaction was committed. It will now wait for the transaction to commit before placing things on the queue.
We have this fix running in one of our Production environments and the error has disappeared.
=> Wait for transaction commit before pushing tasks

temba/channels/handlers.py, temba/channels/models.py, temba/channels/tests.py, temba/channels/views.py
This allows messages and events from Junebug to be authenticated if the channel has a token specified.
=> Add Token Authentication to the Junebug handler

temba/airtime/models.py, temba/airtime/tests.py
Reobone received this email from TransferTo:
> We just upgraded our highly available infrastructure and setup a new Airtime
> API endpoint that provides better performance and security with the support
> of TLS 1.2.
>
> Please update your applications now to call this new endpoint (new Domain name
> & IP) https://airtime.transferto.com/cgi-bin/shop/topup
> (instead of https://fm.transfer-to.com/cgi-bin/shop/topup).
>
> The current endpoint will remain available over the next few weeks to give you
> time to test and perform the migration safely, you can already access it using
> your existing credentials. No other changes are expected in your configuration.
=> Update TransferTo API URL

temba/api/models.py, temba/flows/tests.py
We have a problem with returning _failures_ that can be acted on.  4XX class errors could potentially be managed and resolved.  Right now we have to return a 200 that provides a failure code as part of the body so we're all to check it.
I'm not entirely this is the right way to do this, but it's a start.
fixes #616
=> Handle 4XX errors for flow management

.travis.yml, temba/channels/courier.py, temba/channels/handlers.py, temba/channels/types/junebug/type.py, temba/flows/models.py, temba/msgs/migrations/0079_populate_msg_session.py, temba/msgs/migrations/0096_populate_attachments.py, temba/utils/email.py, travis.sh
This pull request involves splitting the Travis build into multiple parts so that it's possible to run just the lint on Python 3.
It may be possible to split the build step further into more steps but I'm not familiar enough with the project yet to know.
This will keep the codebase Python 3-friendly and allow fixing the tests gradually over time.
=> Run lint on Python 3

media/test_flows/color.json, temba/api/models.py, temba/api/tests.py, temba/flows/tests.py
This PR includes a quick adjustment to the flow webhook to automatically include organization info and the flow's revision ID in the JSON payload. 
- Including organization info in the payload would make it trivial to use common webhook endpoints in multi-tenant rapidpro installs; without the need for users to input org-specific urls/headers (less risk of human error/mixing things up). 
- Including the revision ID allows for more precise analysis of flow results over time, as the flows are fine-tuned. A/B testing of sorts. 
Adding org info was pretty straightforward. Revision id proved to be slightly trickier - I ended up settling on using the metadata dict as it seemed to safely contain the needed info. 
Always open to suggestions!
=> Include organization and revision IDs in flow webhook events

temba/api/support.py, temba/api/v2/tests.py, temba/settings_common.py
This is a response to the call for help on issue #760 
The logic is entirely the same as Token Authentication logic with one extra step of verifying if the token owner has the same username as the one provided in the credentials.
Let me know what you think
=> adding HTTP Basic Authentication for API

_docs/courier.md, _docs/mailroom.md
This should be a more accurate nginx config for systems that use both mailroom and courier proxied through the same nginx instance.
=> adding regex to match pattern at the beginning of location

templates/frame.haml
Indent the `brand.head_includes` and IE9 shim slightly so that when rendered into HTML, the code results inside the header rather than between the `<head>` and `<body>` tags.
=> Fix `frame.haml` template

temba/settings_common.py
Based on the comments in settings_common.py, we've been using a relative STORAGE_URL value of `/media/` with many limited successes. However, the relative URL didn't work with the Twilio channel and we spent some time debugging this.
This change proposes a clarification to the comment in settings_common.py so it is clear that this should be an absolute URL when set
=> Clarify that STORAGE_URL should be an absolute URL

templates/channels/types/facebookapp/claim.haml
Just implemented the param `limit` set to 200. 
@rowanseymour
=> Set max fba pages limit to 200

temba/api/support.py
Check that a user is authenticated before getting org throttle settings
=> Use Default Throttle Rates for Unauthenticated

temba/request_logs/tasks.py
Recently I did an investigation on this task, I found a performance problem in how the query was being made, after that I wrote this issue: https://github.com/rapidpro/rapidpro/issues/1680 
I was recommended to open a Pull Request with the suggested fixes, and here it is. I based myself on the `trim_flow_sessions` task because it is a very performant task.
=> Improve `trim_http_logs_task` performance by splitting the query
